version: "2"
services:
  web:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "8090:8090"
    links:
      - mongo
  mongo:
    image: dhermanns/rpi-mongo
    ports:
      - "27018:27017"
    volumes_from:
      - mongodata
  mongodata:
    image: tianon/true
    volumes:
        - /data/db
